# generated by datamodel-codegen:
#   filename:  last_matches.json
#   timestamp: 2026-06-25T14:01:40+00:00

from __future__ import annotations

from pydantic import Field
from pydantic.dataclasses import dataclass
from typing_extensions import TypeAliasType


@dataclass
class GameType:
    id: str | None = None
    name: str | None = None


@dataclass
class Image:
    path: str | None = None


@dataclass
class Map:
    id: str | None = None
    name: str | None = None
    image: Image | None = None


@dataclass
class MatchStat:
    gameType: GameType | None = None
    isCustomMatch: bool | None = None
    mapName: str | None = None
    matchDuration: float | None = None
    matchStartTime: int | None = None
    specialEventId: str | None = None
    map: Map | None = None


@dataclass
class PostGameStat:
    DBD_SlasherScoreCat_Hunter: int | None = None
    DBD_SlasherScoreCat_Deviousness: int | None = None
    DBD_SlasherScoreCat_Brutality: int | None = None
    DBD_SlasherScoreCat_Sacrifice: int | None = None
    DBD_CamperScoreCat_Objectives: int | None = None
    DBD_CamperScoreCat_Altruism: int | None = None
    DBD_CamperScoreCat_Survival: int | None = None
    DBD_CamperScoreCat_Boldness: int | None = None


@dataclass
class Emblem:
    emblem_id: str | None = None
    emblem_name: str | None = None
    emblem_quality: str | None = None


@dataclass
class CharacterName:
    id: str | None = None
    name: str | None = None
    image: Image | None = None


@dataclass
class AddOn:
    id: str | None = None
    name: str | None = None
    image: Image | None = None


@dataclass
class Image3:
    path: str | None = None
    background: str | None = None


@dataclass
class Offering:
    id: str | None = None
    name: str | None = None
    image: Image3 | None = None


@dataclass
class Image4:
    path: str | None = None


@dataclass
class Perk:
    id: str | None = None
    name: str | None = None
    image: Image4 | None = None


@dataclass
class Power:
    id: str | None = None
    name: str | None = None
    image: Image4 | None = None


@dataclass
class CharacterLoadout:
    addOns: list[AddOn] | None = None
    offering: Offering | None = None
    perks: list[Perk] | None = None
    power: Power | None = None


@dataclass
class PlayerStatus:
    id: str | None = None
    image: Image4 | None = None
    name: str | None = None


@dataclass
class PlayerStat:
    bloodpointsEarned: int | None = None
    characterLevel: int | None = None
    platform: str | None = None
    postGameStat: PostGameStat | None = None
    leaderboardScore: int | None = None
    emblems: list[Emblem] | None = None
    characterClass: None = Field(None)
    characterName: CharacterName | None = None
    playerTimeInMatch: int | None = None
    characterLoadout: CharacterLoadout | None = None
    playerRole: str | None = None
    killerMatchStatus: str | None = None
    prestigeLevel: int | None = None
    playerStatus: PlayerStatus | None = None


@dataclass
class PostGameStat1:
    DBD_CamperScoreCat_Objectives: int | None = None
    DBD_CamperScoreCat_Altruism: int | None = None
    DBD_CamperScoreCat_Boldness: int | None = None
    DBD_CamperScoreCat_Survival: int | None = None
    DBD_SlasherScoreCat_Hunter: int | None = None
    DBD_SlasherScoreCat_Deviousness: int | None = None
    DBD_SlasherScoreCat_Brutality: int | None = None
    DBD_SlasherScoreCat_Sacrifice: int | None = None


@dataclass
class CharacterName1:
    id: str | None = None
    name: str | None = None
    image: Image4 | None = None


@dataclass
class AddOn1:
    id: str | None = None
    name: str | None = None
    image: Image4 | None = None


@dataclass
class Image9:
    path: str | None = None
    background: str | None = None


@dataclass
class Offering1:
    id: str | None = None
    name: str | None = None
    image: Image9 | None = None


@dataclass
class Image10:
    path: str | None = None


@dataclass
class Perk1:
    id: str | None = None
    name: str | None = None
    image: Image10 | None = None


@dataclass
class Power1:
    id: str | None = None
    name: str | None = None
    image: Image10 | None = None


@dataclass
class CharacterLoadout1:
    addOns: list[AddOn1] | None = None
    offering: Offering1 | None = None
    perks: list[Perk1] | None = None
    power: Power1 | None = None


@dataclass
class PlayerStatus1:
    id: str | None = None
    name: str | None = None
    image: Image10 | None = None


@dataclass
class OpponentStatItem:
    bloodpointsEarned: int | None = None
    characterLevel: int | None = None
    platform: str | None = None
    postGameStat: PostGameStat1 | None = None
    leaderboardScore: int | None = None
    emblems: list[Emblem] | None = None
    characterClass: None = Field(None)
    characterName: CharacterName1 | None = None
    playerTimeInMatch: int | None = None
    characterLoadout: CharacterLoadout1 | None = None
    playerRole: str | None = None
    playerStatus: PlayerStatus1 | None = None
    prestigeLevel: int | None = None
    killerMatchStatus: str | None = None


@dataclass
class ModelItem:
    matchStat: MatchStat | None = None
    playerStat: PlayerStat | None = None
    opponentStat: list[OpponentStatItem] | None = None


LastMatchesModel = TypeAliasType("Model", list[ModelItem] | None)
